version: "3.9"
services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
  container_name: server
  hostname: app
  restart: always
  ports:
    - "9000:9000"
  volumes:
    - './server:/server'
    - '/server/node_modules'
  environment:
    - NODE_ENV=development
  networks:
    - iab330
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client_dev
    hostname: client_dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - '/app/node_modules'
    stdin_open: true
    tty: true
    networks:
      - iab330
networks:
  iab330:
    external: true